"""Phase 8 — XAI Layer Integration Tests.

Tests verify:
    - All four XAI output files exist and have correct structure.
    - SHAP attributions: all 18 features present, |attribution| sum > 0.
    - GNN subgraphs: nodes/edges/feature_importance fields non-empty.
    - Evidence trails: all required fields present, triggered_rules non-empty for flagged.
    - Composite scores: bounded [0, 1], internal consistency with evidence trails.
    - End-to-end consistency: composite.risk_gnn matches evidence_trail.risk_score.

These are integration tests — they skip gracefully if Docker services are down
(the XAI JSON files are pre-generated by the scripts, not regenerated here).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

# ---------------------------------------------------------------------------
# Path bootstrap (same as other test files in this project)
# ---------------------------------------------------------------------------
_BACKEND = Path(__file__).resolve().parents[1]
_PROJECT_ROOT = _BACKEND.parent
if str(_BACKEND) not in sys.path:
    sys.path.insert(0, str(_BACKEND))

from app.config import settings

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SHAP_PATH = Path(settings.shap_attributions_path)
GNN_PATH = Path(settings.gnn_subgraphs_path)
TRAILS_PATH = Path(settings.evidence_trails_path)
COMPOSITE_PATH = Path(settings.composite_risk_scores_path)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_json(path: Path) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _skip_if_missing(path: Path, reason: str):
    """Return a pytest.mark.skipif decorator if path does not exist."""
    return pytest.mark.skipif(not path.exists(), reason=reason)


# ---------------------------------------------------------------------------
# XAI-A: SHAP attributions
# ---------------------------------------------------------------------------

@pytest.mark.skipif(not SHAP_PATH.exists(), reason="shap_attributions.json not yet generated — run explain_autoencoder.py")
class TestSHAPAttributions:
    def test_file_is_nonempty(self):
        data = _load_json(SHAP_PATH)
        assert isinstance(data, dict), "shap_attributions.json must be a dict keyed by txid"
        assert len(data) > 0, "shap_attributions.json is empty"

    def test_structure_per_txid(self):
        """Each txid should have a list of 18 feature attribution dicts."""
        data = _load_json(SHAP_PATH)
        sample_txids = list(data.keys())[:10]
        for txid in sample_txids:
            waterfall = data[txid]
            assert isinstance(waterfall, list), f"Waterfall for {txid} must be a list"
            assert len(waterfall) == 18, (
                f"Expected 18 features for {txid}, got {len(waterfall)}"
            )
            for entry in waterfall:
                assert "feature" in entry, "Missing 'feature' key"
                assert "attribution" in entry, "Missing 'attribution' key"
                assert "value" in entry, "Missing 'value' key"
                assert isinstance(entry["attribution"], float), "'attribution' must be float"

    def test_sorted_by_magnitude(self):
        """Waterfall entries must be sorted by |attribution| descending."""
        data = _load_json(SHAP_PATH)
        sample_txids = list(data.keys())[:5]
        for txid in sample_txids:
            waterfall = data[txid]
            mags = [abs(e["attribution"]) for e in waterfall]
            assert mags == sorted(mags, reverse=True), (
                f"Waterfall for {txid} is not sorted by |attribution| descending"
            )

    def test_attribution_sum_nonzero(self):
        """At least some attributions must be nonzero — ensures SHAP actually ran."""
        data = _load_json(SHAP_PATH)
        sample_txids = list(data.keys())[:10]
        for txid in sample_txids:
            total_mag = sum(abs(e["attribution"]) for e in data[txid])
            assert total_mag > 0, f"All attributions are zero for {txid} — SHAP may have failed"

    def test_all_18_feature_names_present(self):
        """All 18 canonical feature names must appear in every waterfall."""
        from app.services.feature_extractor import FEATURE_NAMES
        data = _load_json(SHAP_PATH)
        sample_txids = list(data.keys())[:5]
        for txid in sample_txids:
            names_in_waterfall = {e["feature"] for e in data[txid]}
            for fname in FEATURE_NAMES:
                assert fname in names_in_waterfall, (
                    f"Feature '{fname}' missing from waterfall of {txid}"
                )


# ---------------------------------------------------------------------------
# XAI-B: GNN subgraphs
# ---------------------------------------------------------------------------

@pytest.mark.skipif(not GNN_PATH.exists(), reason="gnn_subgraphs.json not yet generated — run explain_graphsage.py")
class TestGNNSubgraphs:
    def test_file_is_nonempty(self):
        data = _load_json(GNN_PATH)
        assert isinstance(data, dict), "gnn_subgraphs.json must be a dict keyed by wallet address"
        assert len(data) > 0

    def test_top_k_count(self):
        data = _load_json(GNN_PATH)
        assert len(data) <= settings.gnn_explainer_top_k, (
            f"gnn_subgraphs.json has {len(data)} entries but top_k={settings.gnn_explainer_top_k}"
        )

    def test_structure_per_wallet(self):
        data = _load_json(GNN_PATH)
        sample = list(data.values())[:5]
        required_keys = {"address", "risk_score", "is_seed", "nodes", "edges", "feature_importance"}
        for wallet in sample:
            assert required_keys.issubset(wallet.keys()), (
                f"Missing keys in subgraph: {required_keys - wallet.keys()}"
            )
            assert isinstance(wallet["nodes"], list)
            assert isinstance(wallet["edges"], list)
            assert isinstance(wallet["feature_importance"], list)
            assert len(wallet["feature_importance"]) == 8, (
                f"Expected 8 feature importances, got {len(wallet['feature_importance'])}"
            )

    def test_target_wallet_in_own_subgraph(self):
        """The explained wallet must appear in its own subgraph nodes."""
        data = _load_json(GNN_PATH)
        sample = list(data.items())[:5]
        for addr, wallet in sample:
            node_addrs = {n["address"] for n in wallet["nodes"]}
            assert addr in node_addrs, (
                f"Target wallet {addr[:20]}... not in its own subgraph nodes"
            )

    def test_risk_score_bounded(self):
        data = _load_json(GNN_PATH)
        for addr, wallet in data.items():
            rs = wallet["risk_score"]
            assert 0.0 <= rs <= 1.0, f"risk_score {rs} out of bounds for {addr[:20]}..."


# ---------------------------------------------------------------------------
# XAI-C: Evidence trails
# ---------------------------------------------------------------------------

@pytest.mark.skipif(not TRAILS_PATH.exists(), reason="evidence_trails.json not yet generated — run build_evidence_trails.py")
class TestEvidenceTrails:
    REQUIRED_KEYS = {
        "address", "cluster_id", "cluster_size", "anomaly_score",
        "anomaly_rank_percentile", "mixing_patterns", "chain_hops",
        "risk_score", "seed_wallet_proximity", "triggered_rules",
    }

    def test_file_is_nonempty(self):
        data = _load_json(TRAILS_PATH)
        assert isinstance(data, dict)
        assert len(data) > 0

    def test_required_fields_present(self):
        data = _load_json(TRAILS_PATH)
        sample = list(data.values())[:20]
        for trail in sample:
            missing = self.REQUIRED_KEYS - trail.keys()
            assert not missing, f"Missing fields in evidence trail: {missing}"

    def test_risk_score_bounded(self):
        data = _load_json(TRAILS_PATH)
        for addr, trail in data.items():
            rs = trail["risk_score"]
            assert 0.0 <= rs <= 1.0, f"risk_score {rs} out of range for {addr[:20]}..."

    def test_anomaly_percentile_bounded(self):
        data = _load_json(TRAILS_PATH)
        for addr, trail in data.items():
            pct = trail["anomaly_rank_percentile"]
            assert 0.0 <= pct <= 100.0, (
                f"anomaly_rank_percentile {pct} out of range for {addr[:20]}..."
            )

    def test_seed_wallets_have_rules(self):
        """Ransomwhere seed wallets in evidence trails must have RANSOMWHERE rule triggered."""
        data = _load_json(TRAILS_PATH)
        seed_file = _PROJECT_ROOT / "data" / "ransomwhere_seeds.json"
        if not seed_file.exists():
            pytest.skip("ransomwhere_seeds.json not found")
        with open(seed_file, "r", encoding="utf-8") as f:
            raw = json.load(f)
        records = raw.get("result", raw) if isinstance(raw, dict) else raw
        seed_addrs = {r["address"] for r in records if isinstance(r, dict) and "address" in r}

        seed_in_trails = [(addr, data[addr]) for addr in seed_addrs if addr in data]
        if not seed_in_trails:
            pytest.skip("No Ransomwhere seeds found in evidence trails")

        for addr, trail in seed_in_trails[:20]:
            rules_text = " ".join(trail["triggered_rules"])
            assert "RANSOMWHERE" in rules_text, (
                f"Seed wallet {addr[:20]}... missing RANSOMWHERE_SEED_ADDRESS rule. "
                f"Got: {trail['triggered_rules']}"
            )

    def test_triggered_rules_are_strings(self):
        data = _load_json(TRAILS_PATH)
        for addr, trail in list(data.items())[:20]:
            for rule in trail["triggered_rules"]:
                assert isinstance(rule, str), (
                    f"triggered_rule {rule!r} is not a string for {addr[:20]}..."
                )


# ---------------------------------------------------------------------------
# XAI-D: Composite scores
# ---------------------------------------------------------------------------

@pytest.mark.skipif(not COMPOSITE_PATH.exists(), reason="composite_risk_scores.json not yet generated — run compute_composite_risk.py")
class TestCompositeScores:
    def test_file_is_nonempty(self):
        data = _load_json(COMPOSITE_PATH)
        assert isinstance(data, dict)
        assert len(data) > 0

    def test_composite_bounded(self):
        data = _load_json(COMPOSITE_PATH)
        for addr, record in data.items():
            score = record["composite_score"]
            assert 0.0 <= score <= 1.0, (
                f"composite_score {score} out of [0,1] for {addr[:20]}..."
            )

    def test_components_present(self):
        data = _load_json(COMPOSITE_PATH)
        required_components = {"risk_score", "anomaly_score", "rule_bonus", "mixing_indicator"}
        sample = list(data.values())[:10]
        for record in sample:
            missing = required_components - record.keys()
            assert not missing, f"Missing composite components: {missing}"

    def test_components_bounded(self):
        data = _load_json(COMPOSITE_PATH)
        for addr, record in list(data.items())[:50]:
            assert record["anomaly_score"] >= 0.0, (
                f"Component anomaly_score={record['anomaly_score']} < 0 for {addr[:20]}..."
            )
            for key in ("risk_score", "rule_bonus", "mixing_indicator"):
                val = record[key]
                assert 0.0 <= val <= 1.0, (
                    f"Component {key}={val} out of [0,1] for {addr[:20]}..."
                )


# ---------------------------------------------------------------------------
# Cross-layer internal consistency
# ---------------------------------------------------------------------------

@pytest.mark.skipif(
    not (TRAILS_PATH.exists() and COMPOSITE_PATH.exists()),
    reason="Both evidence_trails.json and composite_risk_scores.json needed"
)
class TestCrossLayerConsistency:
    def test_composite_risk_gnn_matches_trail_risk_score(self):
        """XAI-D composite.risk_score must equal XAI-C trail.risk_score."""
        trails = _load_json(TRAILS_PATH)
        composites = _load_json(COMPOSITE_PATH)

        # Check up to 50 addresses that appear in both
        common = [a for a in list(composites.keys())[:200] if a in trails][:50]
        assert len(common) > 0, "No overlapping addresses between trails and composites"

        for addr in common:
            trail_rs = round(float(trails[addr]["risk_score"]), 4)
            comp_gnn = round(float(composites[addr]["risk_score"]), 4)
            assert abs(trail_rs - comp_gnn) < 0.0001, (
                f"risk_score mismatch for {addr[:20]}...: "
                f"trail.risk_score={trail_rs} vs composite.risk_score={comp_gnn}"
            )

    def test_all_composite_wallets_have_trail(self):
        """Every wallet in composite_risk_scores must have an evidence trail."""
        trails = _load_json(TRAILS_PATH)
        composites = _load_json(COMPOSITE_PATH)
        missing = [a for a in composites if a not in trails]
        assert len(missing) == 0, (
            f"{len(missing)} wallets in composites missing from evidence trails: "
            f"{missing[:5]}"
        )
